name: Tag version in Git

on:
  workflow_call:

jobs:
  tag-version-git:
    name: Tag version in GIT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag with version
        env:  
          # TODO: parameterize this from the cli when ready
          GIT_USER: kiran.siddagangappa
          GIT_MAIL: kiran.siddagangappa@analog.com
        run: |
          vers=`python3 -c "
          import configparser
          read_version = configparser.ConfigParser()
          read_version.read('VERSION.ini')
          version = read_version.get('APP', 'version')
          print(version)"`

          git config user.name "$GIT_USER"
          git config user.email "$GIT_MAIL"
          message="Tagged by Automated deploy in dev job, Run Number: $GITHUB_RUN_ID"
          git tag "$vers" -m "$message"
          git push origin "$vers"
          echo "git tag '$vers' created"
